name: CI/CD for Flask Todo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          echo "No tests yet!"

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/flask-todo:$GITHUB_SHA .

      - name: Push Docker image to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker gcr.io
      - name: Push Image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/flask-todo:$GITHUB_SHA
